apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
      - name: backend-db
        image: postgis/postgis:16-3.4-alpine
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-db
spec:
  selector:
    app: backend-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer